# Title of the page
title: "Thomas's Life"
# Your name
author: Thomas Busch
# Show a link to LinkedIn in the header intro. Comment out to disable.
# linkedin: https://www.linkedin.com/in/thomas-busch-57a95160/
# Show a link at the top of your timeline to your main personal site
# Comment this out to disable
personal_site:
  url: https://curacomputers.com
  title: curacomputers
# Show today's marker at the end of the timeline
show_today: true

# Your timeline is split into periods (e.g., decades, childhood/teens/adult, "Before Timeliner"/"After Timeliner", etc)
# Each period has a list of events formatted as `- date: title`. If you don't want to have period dividers, leave out the name field.
periods:
  - events:
    - March 29 1993: "ğŸ‘¶ Thomas is born in Hamilton, Ontario."
    - September 1997: "Jr Kindergarten - Bridgeport Public School"
    - September 1998: "Sr Kindergarten - Bridgeport Public School"
    - September 1999: "Grade 1 - Lincoln Heights"
  - name: 2000's
    events:
    - January 1 2000: "The World Explodes!....Sike"
    - March 29 2000: "ğŸ‚ Thomas turns 7. It's a new millennium."
    - September 2000: "Grade 2 - Lincoln Heights"
    - September 2001: "Grade 3 - Lincoln Heights"
    - September 2002: "Grade 4 - Lincoln Heights"
    - December 2002: "Grade 4 - Home School"
    - September 2003: "Grade 5 - Lincoln Heights"
    - September 2004: "Grade 6 - Lincoln Heights"
    - September 2005: "Grade 7 - Lincoln Heights"
    - September 2006: "Grade 8 - Lincoln Heights"
    - December 2006: "Grade 8 - Home School"
    - September 2007: "Grade 9 - Bluevale Collegiate Institute"
    - September 2007: "Met Chase - I sat in the wrong seat in Business class, ended up being beside Chase, we became fast friends"
    - November 2007: "Moved to 371 Victoria St S"
    - January 1 2008: "Grade 9 - Kitchener Collegiate Institute"
    - September 1 2008: "Grade 10 - Kitchener Collegiate Institute"
    - September 1 2009: "Grade 11 - Kitchener Collegiate Institute"
    - November 2009: >-
        ğŸ“· Link Example <a href="https://curacomputers.com" target="_blank" rel="noopener"
        title="See some of my photos">Link example</a>.
  - name: 2010's
    events:
    - September 1 2010: "Grade 12 - Kitchener Collegiate Institute"
    - June 2010: "âœˆï¸ test."
    - September 1 2011: "Grade 13 - Kitchener Collegiate Institute - Finish Specialist High Skills Major"
    - June 02 2014: "ğŸ’– Saw Danny for the first time, I knew I had to talk to her"
    - June 17 2014: "First time playing boardgames with Danny"
    - September 13 2014: "ğŸ“ Started A+ CE course at Conestoga College"
  - name: 2020's
    events:
    - May 2020: "Thomas goes crazy"
    - March 29 2023: | 
        Danny surprised me on our trip to Toronto, had Melissa, Daniella, Louis, and Cameron waiting on the GO Train.\n
        We all went to Starbucks for a free birthday drink and went to the Old Spaghetti Factory
    - May 16 2023: "ğŸ“ Started the Cyber Security Program at Conestoga College"
