# Title of the page
title: "Thomas's Life"
# Your name
author: Thomas Busch
# Show a link to LinkedIn in the header intro. Comment out to disable.
# linkedin: https://www.linkedin.com/in/thomas-busch-57a95160/
# Show a link at the top of your timeline to your main personal site
# Comment this out to disable
personal_site:
  url: https://curacomputers.com
  title: curacomputers
# show today marker at end of timeline
show_today: true

# Your timeline is split into periods (e.g., decades, childhood/teens/adult, "Before Timeliner"/"After Timeliner", etc)
# Each period has a list of events formatted as `- date: title`. If you don't want to have period dividers, leave out the name field.
periods:
  - events:
    - March 29 1993: "ğŸ‘¶ Thomas is born in Hamilton, Ontario."
  - name: 2000's
    events:
    - October 2000: "ğŸ‚ Thomas turns 7. It's a new millennium."
    - November 2009: >-
        ğŸ“· Link Example <a href="https://curacomputers.com" target="_blank" rel="noopener"
        title="See some of my photos">Link example</a>.
  - name: 2010's
    events:
    - June 2010: "âœˆï¸ test."
  - name: 2020's
    events:
    - May 2020: "Thomas goes crazy"
